# Generated by Django 5.0.3 on 2024-03-18 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0003_alter_leadstasks_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadstasks",
            name="lead_source",
        ),
    ]
