# Generated by Django 5.0.3 on 2024-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0004_remove_leadstasks_lead_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadstasks",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
