# Generated by Django 5.0.3 on 2024-03-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0005_leadstasks_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadstasks",
            name="task_title",
            field=models.CharField(default="Add Task Title", max_length=255),
        ),
    ]
