# Generated by Django 5.0.3 on 2024-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0008_remove_leadstasks_status_leadsnotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadstasks",
            name="lead_stage",
            field=models.CharField(
                choices=[
                    ("Basic Discussion", "Basic Discussion"),
                    ("Interested", "Interested"),
                    ("Not Interested", "Not Interested"),
                    ("Rented Car", "Rented Car"),
                ],
                max_length=100,
            ),
        ),
    ]
