# Generated by Django 5.0.3 on 2024-03-18 11:16

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0009_alter_leadstasks_lead_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SendMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=255)),
                (
                    "message",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "receiver",
                    models.ManyToManyField(
                        related_name="receivers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
