# Generated by Django 5.0.3 on 2024-03-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0010_sendmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendmail",
            name="sender",
            field=models.CharField(default="sandcitydubai@gmail.com", max_length=100),
        ),
    ]
