# Generated by Django 5.0.1 on 2024-01-11 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTypes',
            fields=[
                ('types_id', models.CharField(default=51787433, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('car_types', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('car_id', models.CharField(default=31977595, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveIntegerField(blank=True, default=2070, null=True)),
                ('desc', models.TextField(blank=True, default='', null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.cartypes')),
            ],
        ),
    ]
