# Generated by Django 5.0.1 on 2024-01-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfeatures',
            name='feature_id',
            field=models.CharField(default=89092779, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2121, null=True),
        ),
    ]
