# Generated by Django 5.0.1 on 2024-01-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_cartypes_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_id',
            field=models.CharField(default=48436940, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2261, null=True),
        ),
        migrations.AlterField(
            model_name='cartypes',
            name='types_id',
            field=models.CharField(default=70287455, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('feature_id', models.CharField(default=55324492, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('features', models.CharField(blank=True, max_length=100, null=True)),
                ('cars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.cars')),
            ],
        ),
    ]
