# Generated by Django 5.0.1 on 2024-01-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_alter_cars_car_id_alter_cars_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfeatures',
            name='feature_id',
            field=models.CharField(default=27033162, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_id',
            field=models.CharField(default=99419038, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2299, null=True),
        ),
        migrations.AlterField(
            model_name='cartypes',
            name='types_id',
            field=models.CharField(default=31408187, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
