# Generated by Django 5.0.1 on 2024-01-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0005_carimages_alter_carfeatures_feature_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfeatures',
            name='feature_id',
            field=models.CharField(default=80114146, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_id',
            field=models.CharField(default=16473635, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2068, null=True),
        ),
        migrations.AlterField(
            model_name='cartypes',
            name='types_id',
            field=models.CharField(default=65000683, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
