# Generated by Django 5.0.1 on 2024-01-13 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0005_alter_carfeatures_feature_id_alter_cars_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2241, null=True),
        ),
        migrations.CreateModel(
            name='CarSpecifications',
            fields=[
                ('specification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body_type', models.CharField(blank=True, max_length=100, null=True)),
                ('engine', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('exterior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('cars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.cars')),
            ],
        ),
    ]
