# Generated by Django 5.0.1 on 2024-01-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0006_alter_cars_year_carspecifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='body_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='exterior_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2525, null=True),
        ),
        migrations.DeleteModel(
            name='CarSpecifications',
        ),
    ]
