# Generated by Django 5.0.1 on 2024-01-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0006_alter_carfeatures_feature_id_alter_cars_car_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimages',
            name='cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.cars'),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='feature_id',
            field=models.CharField(default=12701623, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_id',
            field=models.CharField(default=32097413, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2468, null=True),
        ),
        migrations.AlterField(
            model_name='cartypes',
            name='types_id',
            field=models.CharField(default=34449376, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
