# Generated by Django 5.0.1 on 2024-01-13 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_cars_body_type_cars_engine_cars_exterior_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='price',
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2483, null=True),
        ),
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('discounted_price', models.PositiveIntegerField(blank=True, default=50, null=True)),
                ('timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('cars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.cars')),
            ],
        ),
    ]
