# Generated by Django 5.0.1 on 2024-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0008_remove_cars_price_alter_cars_year_carprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='category',
            field=models.CharField(choices=[('premium', 'Premium'), ('economy', 'Economy'), ('sports', 'Sports'), ('7seaters', '7 Seaters')], default='premium', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2721, null=True),
        ),
    ]
