# Generated by Django 5.0.1 on 2024-01-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0016_remove_cars_category_remove_cars_car_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='category',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Economy', 'Economy'), ('Sports', 'Sports'), ('7Seaters', '7Seaters')], default='Premium', max_length=20),
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_type',
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2640, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.cartypes'),
        ),
    ]
