# Generated by Django 5.0.1 on 2024-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0017_cars_category_remove_cars_car_type_alter_cars_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2031, null=True),
        ),
    ]
