# Generated by Django 5.0.2 on 2024-02-27 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rentalapp",
            "0031_country_capital_country_currencies_country_languages_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="forgot_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_activity_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="online_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_active_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2096, null=True),
        ),
    ]
