# Generated by Django 5.0.2 on 2024-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rentalapp",
            "0032_profile_forgot_password_token_profile_is_verified_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email_token",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_email_verified",
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2507, null=True),
        ),
    ]
