# Generated by Django 5.0.2 on 2024-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0033_remove_profile_email_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2628, null=True),
        ),
    ]
