# Generated by Django 5.0.2 on 2024-02-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0036_alter_cars_year_usernotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2674, null=True),
        ),
    ]
