# Generated by Django 5.0.2 on 2024-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0037_alter_cars_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cars",
            name="category",
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2414, null=True),
        ),
    ]
