# Generated by Django 5.0.2 on 2024-02-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0040_cartypes_price_detail_alter_cars_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="actual_price",
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name="cars",
            name="discounted_price",
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2788, null=True),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rentalapp.cars"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CarPrice",
        ),
    ]
