# Generated by Django 5.0.2 on 2024-02-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0043_alter_cars_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2412, null=True),
        ),
    ]
