# Generated by Django 5.0.2 on 2024-02-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0045_remove_booking_pickup_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_day",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2072, null=True),
        ),
    ]
