# Generated by Django 5.0.2 on 2024-02-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0046_booking_total_day_alter_cars_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="total_day",
        ),
        migrations.AddField(
            model_name="booking",
            name="pickup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2017, null=True),
        ),
    ]
