# Generated by Django 5.0.2 on 2024-03-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0047_remove_booking_total_day_booking_pickup_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2499, null=True),
        ),
    ]
