# Generated by Django 5.0.2 on 2024-03-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0049_alter_cars_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNewsletters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("is_subscribe", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2065, null=True),
        ),
    ]
