# Generated by Django 5.0.2 on 2024-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0052_alter_cars_year_blogsdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2939, null=True),
        ),
    ]
