# Generated by Django 5.0.2 on 2024-03-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0055_alter_cars_year_carreviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carreviews",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    (5, "★★★★★ - 5 Stars"),
                    (4, "★★★★☆ - 4 Stars"),
                    (3, "★★★☆☆ - 3 Stars"),
                    (2, "★★☆☆☆ - 2 Stars"),
                    (1, "★☆☆☆☆ - 1 Stars"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2945, null=True),
        ),
    ]
