# Generated by Django 5.0.2 on 2024-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0059_profile_wishlists_alter_cars_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2628, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="wishlists",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="wishlists", to="rentalapp.cars"
            ),
        ),
    ]
