# Generated by Django 5.0.2 on 2024-03-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0061_alter_cars_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2192, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="wishlists",
            field=models.ManyToManyField(related_name="wishlists", to="rentalapp.cars"),
        ),
    ]
