# Generated by Django 5.0.2 on 2024-03-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0064_alter_cars_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2204, null=True),
        ),
        migrations.DeleteModel(
            name="UserWishlists",
        ),
    ]
