# Generated by Django 5.0.2 on 2024-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0065_alter_cars_year_delete_userwishlists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2660, null=True),
        ),
    ]
