# Generated by Django 5.0.2 on 2024-03-05 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0066_alter_cars_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=2034, null=True),
        ),
        migrations.CreateModel(
            name="UserWishlists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.profile",
                    ),
                ),
                (
                    "wishlists",
                    models.ManyToManyField(
                        related_name="wishlists", to="rentalapp.cars"
                    ),
                ),
            ],
        ),
    ]
