# Generated by Django 5.0.2 on 2024-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0069_profile_wishlists_alter_cars_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="car_number",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="cars",
            name="year",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
