# Generated by Django 5.0.2 on 2024-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0070_cars_car_number_alter_cars_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="car_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
