# Generated by Django 5.0.2 on 2024-03-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0071_alter_cars_car_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_mode",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
