# Generated by Django 5.0.2 on 2024-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0072_booking_created_at_booking_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
