# Generated by Django 5.0.2 on 2024-03-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0073_booking_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="transaction_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="pdf/transaction_pdf/"
            ),
        ),
    ]
