# Generated by Django 5.0.2 on 2024-03-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0074_booking_transaction_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_days",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
