# Generated by Django 5.0.2 on 2024-03-08 11:07

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0075_booking_total_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "profile_image",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "created_on",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "verification_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "verification_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "is_verified",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "forgot_password_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("online_status", models.BooleanField(default=False)),
                ("last_activity_time", models.DateTimeField(blank=True, null=True)),
                (
                    "total_active_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical profile",
                "verbose_name_plural": "historical profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
