# Generated by Django 5.0.2 on 2024-03-09 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0076_historicalprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalProfile",
        ),
    ]
