# Generated by Django 5.0.2 on 2024-03-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0077_delete_historicalprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(blank=True, default="", null=True)),
                ("answer", models.TextField(blank=True, default="", null=True)),
            ],
        ),
    ]
