# Generated by Django 5.0.2 on 2024-03-09 13:40

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0079_alter_faq_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("desc", models.TextField(blank=True, default="", null=True)),
                ("keywords", models.TextField(blank=True, default="", null=True)),
                (
                    "page_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/custom_page/"
                    ),
                ),
                ("body", django_ckeditor_5.fields.CKEditor5Field()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
        ),
    ]
