# Generated by Django 5.0.2 on 2024-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0080_custompage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custompage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
