# Generated by Django 5.0.3 on 2024-03-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0081_alter_custompage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/media/assets/images/favicon.png', null=True, upload_to='images/profile/'),
        ),
    ]
