# Generated by Django 5.0.3 on 2024-03-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0082_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
