# Generated by Django 5.0.3 on 2024-03-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0083_booking_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='is_available',
            new_name='in_stock',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='in_stock',
        ),
    ]
