# Generated by Django 5.0.3 on 2024-03-15 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0085_carfeatures_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carfeatures",
            name="slug",
        ),
    ]
