# Generated by Django 5.0.3 on 2024-03-16 04:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0086_remove_carfeatures_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsdetail",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
