# Generated by Django 5.0.3 on 2024-03-16 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0087_alter_blogsdetail_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsdetail",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
