# Generated by Django 5.0.3 on 2024-03-16 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0090_alter_blogsdetail_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
