# Generated by Django 5.0.3 on 2024-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0091_contactus_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="wishlists",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="wishlists", to="rentalapp.cars"
            ),
        ),
    ]
