# Generated by Django 5.0.3 on 2024-03-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0094_alter_booking_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="company_address",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
