# Generated by Django 5.0.3 on 2024-03-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0096_booking_car_pickup_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="cars",
            name="marketing_price",
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
    ]
