# Generated by Django 5.0.3 on 2024-03-26 07:18

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rentalapp", "0097_cars_marketing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="desc",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CarRentalPeriodPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "two_days_price",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "three_to_six_days_price",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "seven_to_29_days_price",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "thirty_days_price",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rentalapp.cars",
                    ),
                ),
            ],
        ),
    ]
